# Generated by Django 4.0 on 2021-12-30 22:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Username')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/avatar', verbose_name='Imagem')),
                ('last_ping', models.DateField(blank=True, null=True, verbose_name='Visto por último')),
                ('status', models.CharField(blank=True, choices=[('online', 'online'), ('online', 'offline')], max_length=10, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['-name'],
            },
        ),
    ]
