# Generated by Django 4.0 on 2022-01-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_ping',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Visto por último'),
        ),
    ]
