# Generated by Django 4.0 on 2022-01-16 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_image_alter_user_username'),
        ('core', '0003_alter_user_image_alter_user_status_and_more'),
    ]

    operations = [
    ]
